id: ICBB0093B
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:54:55.173427
last_modified: 2023-02-09 14:54:55.173559
source_metadata:
  title: 'RK: Bodhisatvapiṭaka'
  language: zh
bases:
  FFE4:
    base_file: FFE4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
